# Site settings
title: Kha Vo blog
email: 
description: "The Magic of Machine Learning."
baseurl: ""
url: "http://voanhkha.github.io"
twitter_username:
github_username:  voanhkha

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
theme: jekyll-theme-cayman
