# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Kha Vo
subtitle: "A versatile AI scientist who won 10 Kaggle competition gold medals!"
email: khahuras@gmail.com
name: Kha Vo
description: >
  The Magic of AI and Machine Learning from a Kaggle Competition Grandmaster.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://voanhkha.github.io" # the base hostname & protocol for your site
cover: "/images/trackML_hits.gif"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Kaggle
    desc: "Posts about Kaggle."

  - cat: AI
    desc: "Posts about AI in general."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: "X/Twitter"
    url: https://x.com/khavo_ds
    desc: Follow me on X (Twitter)
    share: true

  - name: "Kaggle"
    icon: K
    username: "Kaggle"
    url: "https://www.kaggle.com/khahuras"
    desc: View my Kaggle profile
    share: true

  - name: Facebook
    icon: facebook
    username: thebencentra
    url: ""
    desc: Friend me on Facebook
    share: false

  - name: GitHub
    icon: github
    username: "Github"
    url: https://github.com/voanhkha
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: "LinkedIn"
    url: https://www.linkedin.com/in/dr-kha-vo/
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username: ""
    url: ""
    desc: Add me to your Circles
    share: False

  - name: YouTube
    icon: youtube
    username: ""
    url: ""
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: ""
    url: ""
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: ""
    url: ""
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username: ""
    url: ""
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username: ""
    url: ""
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username: ""
    url: ""
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username: ""
    url: ""
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: ""
    url: ""
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username: ""
    url: ""
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username: ""
    url: ""
    desc: Share to Reddit
    share: true



# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/voanhkha/voanhkha.github.io"
    os_rcs_type: "git"
    os_src: "https://github.com/voanhkha/voanhkha.github.io.git"
