# Site settings
title: Kha Vo
email: khahuras@gmail.com
description: "The Magic of Machine Learning."
baseurl: ""
url: "http://voanhkha.github.io"
twitter_username: khavo_ds
github_username:  voanhkha

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
